---
title: Alistair Johnstone | Freelance Analytics Developer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: alsjohnstone@gmail.com
description: Freelance Analytics Developer
logo: /assets/images/bar-chart-small.png
baseurl: 
url: https://alsjohnstone.com
paginate: 5
name: Als Johnstone
bio: Freelance Web Analytics Developer working primarily with the Google Stack (Google Analytics, Google Tag Manager, Data Studio, BigQuery)
author_image: /assets/images/bar-chart-small.png
twitter_username: alsjohnstone
github_username: alsjohnstone
analytics_id: ''
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate